CREATE DATABASE DIVPANT;
USE DIVPANT;
#DROP DATABASE DIVPANT;

CREATE TABLE DIRECCIONES(
	ID_D VARCHAR(10) PRIMARY KEY NOT NULL,
    CALLE VARCHAR(30) NOT NULL,
    NUMERO NUMERIC(3) NOT NULL,
    CP NUMERIC(5) NOT NULL
);

CREATE TABLE EMPLEADOS(
    ID_E VARCHAR(10) PRIMARY KEY NOT NULL,
    NOMBRE_E NUMERIC(15) NOT NULL,
    APELLIDO_E VARCHAR(25) NOT NULL,
    CONTRA_E VARCHAR(30) NOT NULL,
    CORREO_E VARCHAR(30) NOT NULL,
    TELEFONO_E NUMERIC(10) NOT NULL,
    ID_D VARCHAR(10) NOT NULL, 
    FOREIGN KEY(ID_D) REFERENCES DIRECCIONES(ID_D) ON UPDATE CASCADE ON DELETE  CASCADE
);

CREATE TABLE TARJETAS(
    NUM_TARJ NUMERIC(16) PRIMARY KEY NOT NULL,
    #NOMBRE_TARJ VARCHAR(15) NOT NULL,
    #APELLIDO_TARJ VARCHAR(25) NOT NULL,
    FECHA_V NUMERIC(2) NOT NULL,
    CVV NUMERIC(4) NOT NULL,
    NIP NUMERIC(4) NOT NULL
);

CREATE TABLE SOCIOS(
	ID_S VARCHAR(10) PRIMARY KEY NOT NULL,
    NUM_CUENTA NUMERIC(10) NOT NULL,
    CONTRA_S VARCHAR(30) NOT NULL,
    NOMBRE_S VARCHAR(15) NOT NULL,
    APELLIDO_S VARCHAR(25) NOT NULL,
	TELEFONO_S NUMERIC(10) NOT NULL,
	CORREO_S VARCHAR(30) NOT NULL,
    SALDO NUMERIC(5,2) NOT NULL,
    ID_D VARCHAR(10) NOT NULL, 
    NUM_TARJ NUMERIC(16) NOT NULL,
    FOREIGN KEY(ID_D) REFERENCES DIRECCIONES(ID_D) ON UPDATE CASCADE ON DELETE  CASCADE,
    FOREIGN KEY(NUM_TARJ) REFERENCES TARJETAS(NUM_TARJ) ON UPDATE CASCADE ON DELETE  CASCADE
);

CREATE TABLE AUTORES(
    ID_A VARCHAR(10) PRIMARY KEY NOT NULL,
    NOMBRE_A VARCHAR(15) NOT NULL,
    APELLIDO_A VARCHAR(25) NOT NULL
);

CREATE TABLE LIBROS(
    ISBN NUMERIC(13) PRIMARY KEY NOT NULL,
    TITULO VARCHAR(25) NOT NULL,
    EDITORIAL VARCHAR(25) NOT NULL
);

CREATE TABLE AUT_LIB(
    ID_A VARCHAR(10) NOT NULL,
    ISBN NUMERIC(13) NOT NULL,
	PRIMARY KEY(ID_A, ISBN)
);

CREATE TABLE ART_LIB(
    ID_AL VARCHAR(10) PRIMARY KEY NOT NULL,
    ISBN NUMERIC(13) NOT NULL,
	PRECIO NUMERIC(4,2) NOT NULL,
    FOREIGN KEY(ISBN) REFERENCES LIBROS(ISBN) ON UPDATE CASCADE ON DELETE  CASCADE
);

CREATE TABLE ART_BIBL(
    ID_AB VARCHAR(10) PRIMARY KEY NOT NULL,
    ISBN NUMERIC(13) NOT NULL,
	MONTO NUMERIC(4,2) NOT NULL,
    FOREIGN KEY(ISBN) REFERENCES LIBROS(ISBN) ON UPDATE CASCADE ON DELETE  CASCADE
);

CREATE TABLE ART_BF(
    ID_ABF VARCHAR(10) PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR(15) NOT NULL,
    TIPO VARCHAR(15) NOT NULL,
	PRECIO NUMERIC(4,2) NOT NULL
);

CREATE TABLE ART_COMP(
	ID_ABF VARCHAR(10),
    ID_C VARCHAR(10),
    PRIMARY KEY(ID_ABF, ID_C)
);

CREATE TABLE COMPRAS(
	ID_C VARCHAR(10) PRIMARY KEY NOT NULL,
    ID_S VARCHAR(10) NOT NULL,
    FECHA NUMERIC(10) NOT NULL,
    FOREIGN KEY(ID_S) REFERENCES SOCIOS(ID_S)
);

CREATE TABLE TRABAJADOR(
    ID_TRAB VARCHAR(10) PRIMARY KEY NOT NULL,
    NOMBRE_T VARCHAR(15) NOT NULL,
    APELLIDO_T VARCHAR(25) NOT NULL
);

CREATE TABLE TRAB_COMPRAS(
	ID_TRAB VARCHAR(10) NOT NULL,
    ID_C VARCHAR(10) NOT NULL,
    PRIMARY KEY(ID_TRAB, ID_C)
);
#INSERT INTO DIRECCIONES VALUES ("0000000001", "EUGENIA", "25", "03100");
#INSERT INTO TARJETAS VALUES ("01234567891234567", "23", "1234", "4321");
#INSERT INTO SOCIOS VALUES ("0000000001", "2163071647", "CONTRA", "HECTOR", "ROSAS", "5532653891", "HECTOR@LIVE.COM", "100.05", "0000000001", "01234567891234567");
#INSERT INTO TRABAJADOR VALUES("0000000001", "FULANO", "EQUIS");
#INSERT INTO COMPRAS VALUES ("0000000001", "0000000001", "23");
#INSERT INTO TRAB_COMPRAS VALUES ("0000000001", "0000000001");
#SELECT * FROM COMPRAS WHERE TRAB_COMPRAS.ID_TRAB = "0000000001";
#SELECT * FROM TRABAJADOR;
#SELECT * FROM TRAB_COMPRAS;
#SELECT * FROM COMPRAS;
#SELECT * FROM SOCIOS;


#▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
#▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
#▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
#▓▓▓▓▓-....:▓▓▓▓▓▓▓+................-▓▓▓▓▓▓▓
#▓▓▓▓▓-....:▓▓▓▓▓▓▓+.................#▓▓▓▓▓▓
#▓▓▓▓▓-....:▓▓▓▓▓▓▓#===========+.....#▓▓▓▓▓▓
#▓▓▓▓▓-....:▓▓▓▓▓▓▓+.....▓▓▓▓▓▓=.....#▓▓▓▓▓▓
#▓▓▓▓▓-....:@...........######*......#▓▓▓▓▓▓
#▓▓▓▓▓-....:@........................#▓▓▓▓▓▓
#▓▓▓▓▓-....:@+++++-.................@▓▓▓▓▓▓▓
#▓▓▓▓▓-....:▓▓▓▓▓▓▓+.....###-.....:@▓▓▓▓▓▓▓▓
#▓▓▓▓▓-....:▓▓▓▓▓▓▓+.....▓▓▓▓+.....-░▓▓▓▓▓▓▓
#▓▓▓▓▓-....:▓▓▓▓▓▓▓+.....▓▓▓▓▓=......#▓▓▓▓▓▓
#▓▓▓▓▓:----+▓▓▓▓▓▓▓*-----▓▓▓▓▓▓@------*▓▓▓▓▓
#▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
#▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
#▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓